export enum OnboardingStatus {
  BUSINESS = 'BUSINESS',
  OWNER = 'OWNER',
  CONTACT = 'CONTACT',
  BANK_STATEMENTS = 'BANK_STATEMENTS',
  AGREEMENT = 'AGREEMENT',
  WAITING_FOR_APPROVAL = 'WAITING_FOR_APPROVAL',
}
