export interface State {
  code: string
  name: string
}

export const states: { [countryCode: string]: State[] } = {
  US: [
    { name: 'Alabama', code: 'AL' },
    { name: 'Alaska', code: 'AK' },
    { name: 'American Samoa', code: 'AS' },
    { name: 'Arizona', code: 'AZ' },
    { name: 'Arkansas', code: 'AR' },
    { name: 'California', code: 'CA' },
    { name: 'Colorado', code: 'CO' },
    { name: 'Connecticut', code: 'CT' },
    { name: 'Delaware', code: 'DE' },
    { name: 'District of Columbia', code: 'DC' },
    { name: 'Florida', code: 'FL' },
    { name: 'Georgia', code: 'GA' },
    { name: 'Guam', code: 'GU' },
    { name: 'Hawaii', code: 'HI' },
    { name: 'Idaho', code: 'ID' },
    { name: 'Illinois', code: 'IL' },
    { name: 'Indiana', code: 'IN' },
    { name: 'Iowa', code: 'IA' },
    { name: 'Kansas', code: 'KS' },
    { name: 'Kentucky', code: 'KY' },
    { name: 'Louisiana', code: 'LA' },
    { name: 'Maine', code: 'ME' },
    { name: 'Maryland', code: 'MD' },
    { name: 'Massachusetts', code: 'MA' },
    { name: 'Michigan', code: 'MI' },
    { name: 'Minnesota', code: 'MN' },
    { name: 'Mississippi', code: 'MS' },
    { name: 'Missouri', code: 'MO' },
    { name: 'Montana', code: 'MT' },
    { name: 'Nebraska', code: 'NE' },
    { name: 'Nevada', code: 'NV' },
    { name: 'New Hampshire', code: 'NH' },
    { name: 'New Jersey', code: 'NJ' },
    { name: 'New Mexico', code: 'NM' },
    { name: 'New York', code: 'NY' },
    { name: 'North Carolina', code: 'NC' },
    { name: 'North Dakota', code: 'ND' },
    { name: 'Northern Mariana Islands', code: 'MP' },
    { name: 'Ohio', code: 'OH' },
    { name: 'Oklahoma', code: 'OK' },
    { name: 'Oregon', code: 'OR' },
    { name: 'Pennsylvania', code: 'PA' },
    { name: 'Puerto Rico', code: 'PR' },
    { name: 'Rhode Island', code: 'RI' },
    { name: 'South Carolina', code: 'SC' },
    { name: 'South Dakota', code: 'SD' },
    { name: 'Tennessee', code: 'TN' },
    { name: 'Texas', code: 'TX' },
    { name: 'U.S. Virgin Islands', code: 'VI' },
    { name: 'Utah', code: 'UT' },
    { name: 'Vermont', code: 'VT' },
    { name: 'Virginia', code: 'VA' },
    { name: 'Washington', code: 'WA' },
    { name: 'West Virginia', code: 'WV' },
    { name: 'Wisconsin', code: 'WI' },
    { name: 'Wyoming', code: 'WY' },
  ],
  CA: [
    { name: 'Alberta', code: 'AB' },
    { name: 'British Columbia', code: 'BC' },
    { name: 'Manitoba', code: 'MB' },
    { name: 'New Brunswick', code: 'NB' },
    { name: 'Newfoundland', code: 'NL' },
    { name: 'Northwest Territories', code: 'NT' },
    { name: 'Nova Scotia', code: 'NS' },
    { name: 'Nunavut', code: 'NU' },
    { name: 'Ontario', code: 'ON' },
    { name: 'Prince Edward Island', code: 'PE' },
    { name: 'Quebec', code: 'QC' },
    { name: 'Saskatchewan', code: 'SK' },
    { name: 'Yukon', code: 'YT' },
  ],
  AU: [
    { name: 'New South Wales', code: 'NSW' },
    { name: 'Northern Territory', code: 'ANT' },
    { name: 'Queensland', code: 'QLD' },
    { name: 'South Australia', code: 'SA' },
    { name: 'Tasmania', code: 'TAS' },
    { name: 'Victoria', code: 'VIC' },
    { name: 'Western Australia', code: 'WAU' },
  ],
  PH: [
    { name: 'Bangsamoro', code: 'BARMM' },
    { name: 'Bicol Region', code: 'PH-05' },
    { name: 'Cagayan Valley', code: 'PH-02' },
    { name: 'Calabarzon', code: 'PH-40' },
    { name: 'Caraga', code: 'PH-13' },
    { name: 'Central Luzon', code: 'PH-03' },
    { name: 'Central Visayas', code: 'PH-07' },
    { name: 'Cordillera Administrative Region', code: 'PH-15' },
    { name: 'Davao Region', code: 'PH-11' },
    { name: 'Eastern Visayas', code: 'PH-08' },
    { name: 'Ilocos Region', code: 'PH-01' },
    { name: 'Metro Manila', code: 'PH-MTM' },
    { name: 'National Capital Region', code: 'PH-00' },
    { name: 'Northern Mindanao', code: 'PH-10' },
    { name: 'Soccsksargen', code: 'PH-12' },
    { name: 'Southwestern Tagalog Region', code: 'MIMAROPA' },
    { name: 'Western Visayas', code: 'PH-06' },
    { name: 'Zamboanga Peninsula', code: 'PH-09' },
  ],
  SG: [
    { name: 'Central Region', code: 'SG-CR' },
    { name: 'East Region', code: 'SG-ER' },
    { name: 'North Region', code: 'SG-NR' },
    { name: 'North-East Region', code: 'SG-NER' },
    { name: 'West Region', code: 'SG-WR' },
  ],
  AF: [
    { name: 'AA-Armed Forces Americas', code: 'AA' },
    { name: 'AE-Armed Forces Other', code: 'AE' },
    { name: 'AP-Armed Forces Pacific', code: 'AP' },
  ],
}
